### ISSUE TITLE
ITSMConfigItem doesn't associate with Ticket

### ISSUE THREAD

**Issue by fabiohdo** [reneeb/otrs-DynamicFieldITSMConfigItem#1]
Hi,

I'm using otrs 6.0.7 and trying to associate an CI with a Ticket but doesn't work.

I got the module from https://opar.perl-services.de/package/R/RE/RENEEB/DynamicFieldITSMConfigItem

Thanks.

**Comment by reneeb** [comment]
If you want to get a link between the CI and the ticket, you have to "Link" them. This addon just provides a new DynamicField type. This is a "one way" information.
