### ISSUE TITLE
Give plz example of Constrictions

### ISSUE THREAD

**Issue by iacsvrn** [reneeb/otrs-DynamicFieldITSMConfigItem#2]
Give plz example, how to create filter constrictions ( [CI-Attribute]::[Object]::[Attribute/Value]::[Mandatory] ) at ITSM::ConfigItem::Class::Databases , i.e.

**Comment by reneeb** [comment]
Hope, this helps: https://github.com/reneeb/otrs-DynamicFieldITSMConfigItem/blob/master/doc/en/DynamicFieldITSMConfigItem.pod
