### ISSUE TITLE
Don't work Class filters

### ISSUE THREAD

**Issue by NvAriec** [reneeb/otrs-DynamicFieldITSMConfigItem#3]
Hello.
OTRS 6.0.18
DynamicFieldITSMConfigItem 6.0.1
Use module DynamicFieldITSMConfigItem
Don't work filters in settings Dynamic Field. Chek one or two classes, but all classes display in Dynamic Field search.

**Comment by reneeb** [comment]
A fixed version is uploaded to OPAR.
